// Builds the module and writes it, and data/LEVELS.DAT, into src/generated/,
// which is committed so installing the package never needs Rust.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { engineSourceHash } from "./engine-sources.ts";

const root = join(import.meta.dirname, "..");
const out = join(root, "src", "generated");
mkdirSync(out, { recursive: true });

execFileSync(
  "cargo",
  [
    "build",
    "--release",
    "--package",
    "supaplex-wasm",
    "--lib",
    "--target",
    "wasm32-unknown-unknown",
  ],
  {
    cwd: root,
    stdio: "inherit",
    env: {
      ...process.env,
      // Keeps the checkout's path out of the module, so every checkout
      // builds the same bytes.
      RUSTFLAGS: `--remap-path-prefix=${root}=supaplex`,
    },
  },
);
const wasm = readFileSync(
  join(
    root,
    "target",
    "wasm32-unknown-unknown",
    "release",
    "supaplex_wasm.wasm",
  ),
);
const source = engineSourceHash(root);

writeFileSync(join(out, "engine.wasm"), wasm);
writeFileSync(
  join(out, "engine.ts"),
  `// Generated by scripts/generate.ts from crates/: do not edit.

/** A hash of the sources this was built from (scripts/engine-sources.ts). */
export const ENGINE_SOURCE: string = ${JSON.stringify(source)};

/** The engine, compiled to WebAssembly (${wasm.length} bytes), base64. */
export const ENGINE_WASM: string = ${JSON.stringify(wasm.toString("base64"))};
`,
);

const levels = readFileSync(join(root, "data", "LEVELS.DAT"));
writeFileSync(
  join(out, "levels.ts"),
  `// Generated by scripts/generate.ts from data/LEVELS.DAT: do not edit.

/** sha256 of data/LEVELS.DAT. */
export const LEVELS_SHA256: string = ${JSON.stringify(createHash("sha256").update(levels).digest("hex"))};

/** The game's 111 levels, 1536 bytes each, base64. */
export const LEVELS_DAT: string = ${JSON.stringify(levels.toString("base64"))};
`,
);

console.log(
  `engine ${wasm.length} bytes (${source}), levels ${levels.length} bytes`,
);
